version: "3.4"
services:
  mysql:
    platform: linux/amd64
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=nikita
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=clientDB
  argon-api:
    platform: linux/amd64
    container_name: argon-api
    restart: always
    build:
        context: .
        dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
        - ../argon-api:/app
        - /app/node_modules
    environment:
        PORT: 3000
        HOST: 0.0.0.0
        DB_HOST: mysql
    depends_on:
      - mysql
    command: npm run start:dev
